#!/bin/sh
. "$(dirname $0)"/common
. "$ETC_PATH"/config

########################################################################################################################
# DEFAULTS
########################################################################################################################
current_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
current_timestamp=$(date +"%Y-%m-%d-%H-%M-%S")

BACKUP_TARGET_DIR="$SHARE_PATH"/backup
GITLAB_DIR="$SHARE_PATH"/gitlab
GITLAB_PACKAGE_CONTROL="$current_dir"/start-stop-status

gitlab_database=$DB_NAME

########################################################################################################################
# Prepare
########################################################################################################################
if ! [ -d "$BACKUP_TARGET_DIR" ]; then
  mkdir -p $BACKUP_TARGET_DIR
fi

########################################################################################################################
# The command line help
########################################################################################################################
display_help() {
    echo "Usage: $0 [option...]" >&2
    echo
    echo "   --backup-target-dir        Target directory for the compressed backup file. default: $BACKUP_TARGET_DIR"
    echo "   --gitlab-dir               GitLab installation directory. default: $GITLAB_DIR"
    echo "   --gitlab-database          GitLab database name. default: $gitlab_database"
    echo
    # echo some stuff here for the -a or --add-options
    exit 1
}

########################################################################################################################
# PARAMETER HANDLING
########################################################################################################################
while [ $# -ge 1 ]; do
    case "$1" in
        --backup-target-dir)
            BACKUP_TARGET_DIR="$2"; shift 2
            if ! [ -d $BACKUP_TARGET_DIR ]; then
                mkdir -p $BACKUP_TARGET_DIR
            fi
        ;;
        --gitlab-dir)
            GITLAB_DIR="$2"; shift 2
            if ! [ -d $GITLAB_DIR ]; then
                echo "--gitlab-dir $GITLAB_DIR not found!"
                exit 1
            fi
        ;;
        --gitlab-database)
            gitlab_database="$2"; shift 2
        ;;

        -h | --help)
            display_help  # Call your function
            exit 0
        ;;
        --) # End of all options
            shift
            break
        ;;
        -*)
            ## or call function display_help
            exit 1
        ;;
        *)  # No more options
            break
        ;;
    esac
done

########################################################################################################################
# VALIDATE PARAMETER DEPENDENCIES
########################################################################################################################
if ! $DOCKER_BIN exec -i $POSTGRESQL_NAME psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $gitlab_database; then
    echo "DATABASE: $gitlab_database do not exists!"
    exit 1
fi

########################################################################################################################
# STOP SYNOLOGY PACKAGE
########################################################################################################################
echo "stopping GitLab"
x=$($GITLAB_PACKAGE_CONTROL stop 2> /dev/null)

########################################################################################################################
# BACKUP
########################################################################################################################
echo "backup config"
config_file_list="synology_gitlab synology_gitlab_db synology_gitlab_redis"
x=$(/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container.Profile version=1 method=export outfile="$BACKUP_TARGET_DIR/synology_gitlab_redis" name=synology_gitlab_redis 2> /dev/null)
x=$(/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container.Profile version=1 method=export outfile="$BACKUP_TARGET_DIR/synology_gitlab_db" name=synology_gitlab_db 2> /dev/null)
x=$(/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container.Profile version=1 method=export outfile="$BACKUP_TARGET_DIR/synology_gitlab" name=synology_gitlab 2> /dev/null)

gitlab_package_fqn=$(jq '.image' < "$BACKUP_TARGET_DIR/synology_gitlab" | tr -d '"')
gitlab_package_name=$(echo $gitlab_package_fqn | cut -f1 -d:)
gitlab_package_version=$(echo $gitlab_package_fqn | cut -f2 -d:)

if [ -f "$ETC_PATH"/config ]; then
    cp "$ETC_PATH"/config $BACKUP_TARGET_DIR"/config"
    config_file_list="$config_file_list config"
fi

if [ -f "$ETC_PATH"/config_container_ports ]; then
    cp "$ETC_PATH"/config_container_ports $BACKUP_TARGET_DIR"/config_container_ports"
    config_file_list="$config_file_list config_container_ports"
fi

if [ -f "$ETC_PATH"/config_custom ]; then
    cp "$ETC_PATH"/config_custom $BACKUP_TARGET_DIR"/config_custom"
    config_file_list="$config_file_list config_custom"
fi

echo "compress gitlab folder"
tar cpfz $BACKUP_TARGET_DIR"/gitlab.tar.gz" --directory=$GITLAB_DIR .


echo "backup gitlab database"
x=$($SYNO_WEBAPI --exec api=SYNO.Docker.Container version=1 method=start name="$POSTGRESQL_NAME" 2> /dev/null)
sleep 3
$DOCKER_BIN exec -t -u postgres $POSTGRESQL_NAME pg_dumpall -c > $BACKUP_TARGET_DIR"/database.sql"

echo "compress everything to a backup file"
tar cfz $BACKUP_TARGET_DIR/$current_timestamp"-gitlab-"$gitlab_package_version".tar.gz" --remove-files --directory="$BACKUP_TARGET_DIR" gitlab.tar.gz database.sql $config_file_list

########################################################################################################################
# FINISH
########################################################################################################################
echo "start GitLab"
x=$($GITLAB_PACKAGE_CONTROL start 2> /dev/null)

echo "backup completed!"
