#!/bin/bash
# Copyright (c) 2000-2017 Synology Inc. All rights reserved.

[ "$SYNOPKG_PKG_STATUS" = UPGRADE ] && exit 0

. "$(dirname "$0")"/common

#[ -f /var/packages/MariaDB10/enabled ] && RunMySQL="yes" || RunMySQL="no"

#ADMIN_ACCOUNT="$wizard_m10_acc"
#ADMIN_PASS="$wizard_m10_pass"

#if [ "$pkgwizard_remove_mysql" = "true" ]; then
#	if [ "$RunMySQL" = "yes" ]; then
#		wizard_admin_info_error="$mariadb10_connect_error"
#		db_admin_permission_error="$m10_admin_permission_error"
#		DBAdminCheck "$ADMIN_ACCOUNT" "$ADMIN_PASS" "$MYSQL10_BIN" || exit 1
#	else
#		log "$sql_not_run"
#	fi
#fi

exit 0
