#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/common
UI_PATH="/usr/syno/synoman/webman/3rdparty/$PKG_NAME"

case "$1" in
	start)
		[ -d "$TARGET_PATH"/ui ] && ln -s "$TARGET_PATH"/ui "$UI_PATH"
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=start name="$REDIS_NAME" && exit 0
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=start name="$POSTGRESQL_NAME" && exit 0
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=start name="$GITLAB_NAME" && exit 0
		exit 1
		;;

	stop)
		rm "$UI_PATH"
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=stop name="$GITLAB_NAME" || exit 1
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=stop name="$POSTGRESQL_NAME" || exit 1
		"$SYNO_WEBAPI" --exec api=SYNO.Docker.Container version=1 method=stop name="$REDIS_NAME"  || exit 1
		exit 0
		;;

	status)
		[ -e "$DOCKER_BIN" ] || exit 1
		docker_version=$(synopkg version Docker | cut -d '-' -f 2)
		if [ "$docker_version" -le 0344 ]; then
			"$DOCKER_BIN" inspect "$GITLAB_NAME" | grep -q "\"SynoStatus\": \"running\"," || exit 1
			"$DOCKER_BIN" inspect "$POSTGRESQL_NAME" | grep -q "\"SynoStatus\": \"running\"," || exit 1
			"$DOCKER_BIN" inspect "$REDIS_NAME"  | grep -q "\"SynoStatus\": \"running\"," || exit 1
		else
			"$DOCKER_BIN" inspect "$GITLAB_NAME" | grep -q "\"Status\": \"running\"," || exit 1
			"$DOCKER_BIN" inspect "$POSTGRESQL_NAME" | grep -q "\"Status\": \"running\"," || exit 1
			"$DOCKER_BIN" inspect "$REDIS_NAME"  | grep -q "\"Status\": \"running\"," || exit 1
		fi
		exit 0
		;;

	*)
		exit 1
		;;
esac
